// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIPAC.API.Data;

#nullable disable

namespace SIPAC.API.Migrations
{
    [DbContext(typeof(SipacDbContext))]
    [Migration("20260901131054_InitialCreateBasiFix")]
    partial class InitialCreateBasiFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SIPAC.API.Entities.AjusteInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAjuste")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AjustesInventario");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsFraccionable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockActual")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockMinimo")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SIPAC.API.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SIPAC.API.Entities.CategoriaTrabajo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias_trabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoComprobanteUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroComprobante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionesDiferencia")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("SIPAC.API.Entities.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CantidadRecibida")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("CompraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("CompraId");

                    b.ToTable("DetallesCompra");
                });

            modelBuilder.Entity("SIPAC.API.Entities.EgresoConsumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ArticuloId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("observacion");

                    b.Property<long>("OrdenTrabajoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orden_trabajo_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("egresos_consumo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PuestoSector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Legajo")
                        .IsUnique();

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("SIPAC.API.Entities.OrdenTrabajo", b =>
                {
                    b.Property<long>("IdOt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_ot");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("observaciones");

                    b.Property<string>("ProblemaReportado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("problema_reportado");

                    b.Property<long>("ResponsableId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("responsable_id");

                    b.Property<string>("SolucionRealizada")
                        .HasColumnType("TEXT")
                        .HasColumnName("solucion_realizada");

                    b.Property<long>("UnidadFuncionalId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unidad_funcional_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("IdOt");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("UnidadFuncionalId");

                    b.ToTable("ordenes_trabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.RegistroBitacoraOt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detalle_cambio");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_hora");

                    b.Property<long>("OrdenTrabajoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orden_trabajo_id");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_operacion");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("registro_bitacora_ot");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Responsable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("responsables");
                });

            modelBuilder.Entity("SIPAC.API.Entities.UnidadFuncional", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Depto")
                        .HasColumnType("TEXT")
                        .HasColumnName("depto");

                    b.Property<string>("Piso")
                        .HasColumnType("TEXT")
                        .HasColumnName("piso");

                    b.Property<string>("SectorEscalera")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sector_escalera");

                    b.HasKey("Id");

                    b.HasIndex("SectorEscalera", "Piso", "Depto");

                    b.ToTable("unidades_funcionales");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SIPAC.API.Entities.AjusteInventario", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Articulo", "Articulo")
                        .WithMany("Ajustes")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.Usuario", "Usuario")
                        .WithMany("Ajustes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Articulo", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SIPAC.API.Entities.AuditLog", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Usuario", "Usuario")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Compra", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIPAC.API.Entities.DetalleCompra", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Articulo", "Articulo")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("SIPAC.API.Entities.EgresoConsumo", b =>
                {
                    b.HasOne("SIPAC.API.Entities.Articulo", "Articulo")
                        .WithMany("Egresos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Egresos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.Usuario", "Usuario")
                        .WithMany("Egresos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIPAC.API.Entities.OrdenTrabajo", b =>
                {
                    b.HasOne("SIPAC.API.Entities.CategoriaTrabajo", "Categoria")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.Responsable", "Responsable")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIPAC.API.Entities.UnidadFuncional", "UnidadFuncional")
                        .WithMany("OrdenesTrabajo")
                        .HasForeignKey("UnidadFuncionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Responsable");

                    b.Navigation("UnidadFuncional");
                });

            modelBuilder.Entity("SIPAC.API.Entities.RegistroBitacoraOt", b =>
                {
                    b.HasOne("SIPAC.API.Entities.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Bitacora")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Articulo", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("DetallesCompra");

                    b.Navigation("Egresos");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("SIPAC.API.Entities.CategoriaTrabajo", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SIPAC.API.Entities.OrdenTrabajo", b =>
                {
                    b.Navigation("Bitacora");

                    b.Navigation("Egresos");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Responsable", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.UnidadFuncional", b =>
                {
                    b.Navigation("OrdenesTrabajo");
                });

            modelBuilder.Entity("SIPAC.API.Entities.Usuario", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("AuditLogs");

                    b.Navigation("Compras");

                    b.Navigation("Egresos");
                });
#pragma warning restore 612, 618
        }
    }
}
